env: prod
component: shipping
params: "CART_ENDPOINT:prod.shipping.cart_endpoint,DB_HOST:prod.rds.endpoint"

schemaLoadJob:
  # Specifies whether a service account should be created
  create: true
  type: mysql


resources:
  limits:
    cpu: 1000m
    #cpu: 1300m
    memory: 2048Mi
    #memory: 3048Mi
  requests:
    cpu: 1000m
    memory: 1500Mi
    #memory: 2500Mi

