#env: prod
component: shipping
params: "CART_ENDPOINT:prod.shipping.cart_endpoint,DB_HOST:prod.rds.endpoint"

#schemaLoadJob:
#  # Specifies whether a service account should be created
#  create: true
#  type: mysql

